### ISSUE TITLE
CUDA out of memory?

### ISSUE THREAD

**Issue by jackiechenxd** [navganti/SIVO#4]
Hi, 

Thanks for sharing your code. I have just built it following your instruction, but I encounter following error when running:
```
F0330 14:27:00.461199  5738 syncedmem.cpp:56] Check failed: error == cudaSuccess (2 vs. 0)  out of memory. 
```
The system has 1080 with 8GB memory. The batch size in .prototxt has been set to 2, which is the minimum requirement. May I know what are the possible causes of this error? Thanks!

**Comment by jackiechenxd** [comment]
Okay, I think it is due to GPU memory issue. 
It could successfully start running after setting the image resolution to 176 * 512, which is half of the original size. But most kitti sequences will lost tracking during the dramatic rotation motion, maybe due to the small image size?

**Comment by navganti** [comment]
Hey @jackiechenxd  - yes, I've run into that error with regards to GPU memory. I was using 12GB of GPU memory so that definitely helped me. I didn't have to reduce my images that small - but it might have been because I was using the basic network, which is much smaller than the standard one.

I would recommend using the basic network with a higher batch size. Although the standard network would typically outperform the basic network (all other factors held equal) having a larger batch size is important for the uncertainty estimation! Using the basic network with a batch size of 6 or so (if you can fit it) is recommended over the standard network with a smaller batch.

**Comment by navganti** [comment]
@jackiechenxd let me know if the basic network runs okay for you! I will close the issue if all goes well :slightly_smiling_face:
